### ISSUE TITLE
The project crashes on startup

### ISSUE THREAD

**Issue by ashtanko** [skydoves/server-driven-compose#1]
Getting error in app start:

### Gradle version:
_8.7_

### Android Studio:
_Ladybug | 2024.2.1 Canary 9_

### Devices:
_Google Pixel 9 Pro XL & Google Pixel 7 Pro and Emulator_

### The error stack-trace:
```text
java.lang.IllegalStateException: Default FirebaseApp is not initialized in this 
process io.getstream.server.driven.compose. Make sure to call FirebaseApp.initializeApp(Context) first.
at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:179)
at com.google.firebase.database.FirebaseDatabase.getInstance(FirebaseDatabase.java:71)
at com.google.firebase.database.DatabaseKt.database(Database.kt:36)
at io.getstream.server.driven.core.network.di.NetworkModule.provideDatabaseReference(NetworkModule.kt:36)
```

The following code does not resolve the issue:
```kotlin
@HiltAndroidApp
class ServerDrivenApp : Application() {
  override fun onCreate() {
    super.onCreate()
    FirebaseApp.initializeApp(this)
  }
}
```

**Comment by ashtanko** [comment]
Update: this happens because the file google-services.json does not exist
The issue can be closed
